version: '3'

services:
  app:
    image: golang:1.21-alpine
    working_dir: /app
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    command: sh -c "go mod download && go run main.go"
    environment:
      - GIN_MODE=release
