info:
  contact: {}
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: liveness probe
      tags:
      - Hello World
swagger: "2.0"
